name: Deploy Static Site to Hostinger

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install -y lftp
      

    - name: Deploy to Hostinger via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_PORT: ${{ secrets.FTP_PORT }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_HOST <<EOF
        set ssl:verify-certificate no
        mirror -R --delete --verbose ./ /public_html
        bye
        EOF
